### ISSUE TITLE
CameraDevice Continuous ExposureMode isn't continous

### ISSUE THREAD

**Issue by allan-o3h** [natmlx/NatDevice#1]
On iOS setting the camera device exposure mode appears to be behave as `AVCaptureExposureModeAutoExpose` instead of as `AVCaptureExposureModeContinuousAutoExposure`.  In that the exposure is set correct when you call this, but if the lighting changes afterwards the exposure does not adjust.

**Comment by olokobayusuf** [comment]
Hey @allan-o3h , thanks for reporting this. And yes, it looks like a bug of omission. We correctly handle focus changes, but not exposure. Will fix this [in 1.2.3](https://docs.natml.ai/natdevice/insiders/changelog#1.2.3-in-beta).

**Comment by olokobayusuf** [comment]
Fixed in [1.2.3](https://github.com/natmlx/NatDevice/releases/tag/1.2.3)
