### ISSUE TITLE
Setter of MediaDeviceQuery.previewResolution does not work correctly.

### ISSUE THREAD

**Issue by acttoz** [natmlx/NatDevice#15]
`
var query = new MediaDeviceQuery(MediaDeviceCriteria.FrontCamera);
cameraDevice = query.current as CameraDevice;
cameraDevice.previewResolution = (600, 270);

`
My code is as above.

But android logcat says:
2022-10-27 16:36:46.601 31143 31171 Debug NatML CameraDevice 1 preview resolution set to (640,360)

Why it says this difference?

**Comment by olokobayusuf** [comment]
This is working as expected. Camera devices support a fixed set of resolutions, so when you set a `previewResolution` or `photoResolution`, what NatDevice does is find a supported resolution closest to what you requested.
