### ISSUE TITLE
Compile error Version 1.3.1 with Unity 2020.3.36

### ISSUE THREAD

**Issue by Alexees** [natmlx/NatDevice#25]
Texture2D.Reinitialize does not exist anymore. Should be replaced with Texture2D.Resize.
Cloud build cannot be used because code changes to the package cache are not possible that easily

10: [2022-11-29T13:27:17Z - Unity] Library\PackageCache\ai.natml.natdevice@1.3.1\Runtime\Outputs\TextureOutput.cs(112,29): error CS1061: 'Texture2D' does not contain a definition for 'Reinitialize' and no accessible extension method 'Reinitialize' accepting a first argument of type 'Texture2D' could be found (are you missing a using directive or an assembly reference?)
11: [2022-11-29T13:27:27Z - Unity] Library\PackageCache\ai.natml.natdevice@1.3.1\Runtime\Outputs\TextureOutput.cs(112,29): error CS1061: 'Texture2D' does not contain a definition for 'Reinitialize' and no accessible extension method 'Reinitialize' accepting a first argument of type 'Texture2D' could be found (are you missing a using directive or an assembly reference?)

**Comment by olokobayusuf** [comment]
[NatDevice (and all other APIs) require Unity 2021.2+](https://docs.natml.ai/natdevice/prelims/requirements).
