### ISSUE TITLE
DllNotFoundException: NatDevice assembly

### ISSUE THREAD

**Issue by alessandroperetti** [natmlx/NatDevice#28]
Hi,
 I am facing with a strange error whenever I try to build the project inside unity:
 
![image](https://user-images.githubusercontent.com/2912857/210852468-c04a06b5-6fd6-462d-8a99-3793fdde8772.png)

The strangeness is that compiling for android device works well. 
I tried to change the `NatDevice` version but nothing works. .

I am currently using those versions:

- NatDevice 1.3.2
- Unity editor 2022.1.0f1
- Linux Ubuntu

Probably, assembly dll is missing? 

I think is a banal error but I have no idea how I can solve it.

Thank you,
AP

**Comment by olokobayusuf** [comment]
Hey there AP, NatDevice currently doesn't have an implementation for Linux. [These are our current platforms](https://docs.natml.ai/natdevice/prelims/requirements). We have longer term plans to support Linux, but not anytime soon.

**Comment by alessandroperetti** [comment]
Thank you very much I missed it.
