### ISSUE TITLE
 NatDevice session token is invalid

### ISSUE THREAD

**Issue by V0odo0** [natmlx/NatDevice#29]
Everything works fine in Editor but I got this error on both Windows (x64) and Android builds right on the app startup. 

`InvalidOperationException: NatDevice session token is invalid. Check your NatML access key and plan.`

* Unity 2021.3.12f
* Il2CPP .NetStandard 2.1
* ![image](https://user-images.githubusercontent.com/10213769/210856850-a404bb92-2c12-41c0-8353-102bd68af977.png)

**Comment by olokobayusuf** [comment]
Hey @V0odo0 is your app's bundle ID different from the bundle ID in Unity's Player Settings? Are you embedding Unity into another app?

**Comment by V0odo0** [comment]
> Hey @V0odo0 is your app's bundle ID different from the bundle ID in Unity's Player Settings? Are you embedding Unity into another app?

My app is not embedded.

What exactly is app's bundle ID in comparison with bundle ID in Unity's Player Settings?

**Comment by olokobayusuf** [comment]
> What exactly is app's bundle ID in comparison with bundle ID in Unity's Player Settings?

<img width="1440" alt="Screenshot 2023-01-06 at 9 19 58 AM" src="https://user-images.githubusercontent.com/17663473/211030341-4a27a2c0-e22b-4682-90a2-40e1f9db057f.png">

This is your bundle ID. If you aren't embedding your app, then what you set in Unity will be the same as the final app binary. Since that doesn't seem to be the case for you, can you share the full, unfiltered logs from `logcat` (for Android) and the `Player.log` (for Windows)?

**Comment by olokobayusuf** [comment]
@V0odo0 can you share the Android logs too? And can you share the `Editor.log` after building the player (for either Android or Windows)? It seems that the session token isn't being set at runtime, which shouldn't ever happen.

**Comment by V0odo0** [comment]
Windows
[Editor.log](https://github.com/natmlx/NatDevice/files/10366712/Editor.log)

**Comment by olokobayusuf** [comment]
@V0odo0 and Android runtime logs? Seems that building from Unity isn't encountering any errors.

**Comment by V0odo0** [comment]
> @V0odo0 and Android runtime logs? Seems that building from Unity isn't encountering any errors.

This project is not targeting for Android currently. I don't think that changing build target will show something that is related to this issue. Both Win & Android builds throws the same exception right on the startup.

**Comment by olokobayusuf** [comment]
> This project is not targeting for Android currently. I don't think that changing build target will show something that is related to this issue. Both Win & Android builds throws the same exception right on the startup.

The reason why I'm asking for the Android logs is to see whether the session token is being set before the error above pops up. We have independent implementations for each platform we support. But as far as I can tell, this function isn't being invoked at runtime, which is what would cause the `session token is invalid` error:

https://github.com/natmlx/NatDevice/blob/750a5a5fca511cd871701a0028db01cfd2d9fbee/Runtime/MediaDeviceQuery.cs#L85-L86

**Comment by V0odo0** [comment]
I fugure it out. 

`Methods marked [RuntimeInitializeOnLoadMethod] are invoked after the game has been loaded. This is after the Awake method has been invoked.`

My app quieries video devices in the first loaded scene on Awake. 

I moved my code to Start but I recommend you to change the token validation behaviour. Either initialize it on demand or move to `[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]`

**Comment by olokobayusuf** [comment]
Will be adding `[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]` to the next update. Thanks for reporting it back.
