### ISSUE TITLE
 audio device return null on buffer

### ISSUE THREAD

**Issue by Vittix** [natmlx/NatDevice#36]
Hello i'm trying to send an audio stream recording mic to an Audio buffer but using StartRunning method on audio device return a null on buffer.

Here following the log of error we get:

ArgumentNullException: Value cannot be null.
Parameter name: array
Unity.Collections.NativeArray1[T]..ctor (System.Single[] array, Unity.Collections.Allocator allocator) (at <685c48cf8f0b48abb797275c046dda6a>:0)
NatML.Devices.AudioBuffer.Wrap (System.Single[] buffer) (at Library/PackageCache/ai.natml.natdevice@1.3.4/Runtime/AudioBuffer.cs:124)
NatML.Devices.AudioBuffer..ctor (NatML.Devices.IMediaDevice1[TSampleBuffer] device, System.Single[] sampleBuffer, System.Int32 sampleRate, System.Int32 channelCount, System.Int64 timestamp) (at Library/PackageCache/ai.natml.natdevice@1.3.4/Runtime/AudioBuffer.cs:58)
NatML.Devices.AudioBuffer.Clone () (at Library/PackageCache/ai.natml.natdevice@1.3.4/Runtime/AudioBuffer.cs:104)
NatML.Devices.Outputs.AudioClipOutput.Update (NatML.Devices.AudioBuffer audioBuffer) (at Library/PackageCache/ai.natml.natdevice@1.3.4/Runtime/Outputs/AudioClipOutput.cs:38)
NatML.Devices.AudioDevice+<>cDisplayClass28_0.<StartRunning>b0 (System.IntPtr sampleBuffer) (at Library/PackageCache/ai.natml.natdevice@1.3.4/Runtime/AudioDevice.cs:98)
NatML.Devices.AudioDevice.OnAudioBuffer (System.IntPtr context, System.IntPtr sampleBuffer) (at Library/PackageCache/ai.natml.natdevice@1.3.4/Runtime/AudioDevice.cs:152)
UnityEngine.Debug:LogException(Exception)
NatML.Devices.AudioDevice:OnAudioBuffer(IntPtr, IntPtr) (at Library/PackageCache/ai.natml.natdevice@1.3.4/Runtime/AudioDevice.cs:155)

**Comment by olokobayusuf** [comment]
This has been fixed in VideoKit. NatDevice has officially been deprecated as it has been merged into [VideoKit](https://github.com/natmlx/VideoKit).
