### ISSUE TITLE
Exposure and focus controls on Windows

### ISSUE THREAD

**Issue by tufeixp** [natmlx/natdevice#9]
Can not set / get exposure value on windows pc!

**Comment by olokobayusuf** [comment]
Heyo, Windows MediaFoundation, the native media API on Windows, does not provide exposure controls. [See this thread](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/2cd63e06-0f88-4bb6-bc5b-c31520990e26/how-to-issue-kspropertysetidextendedcameracontrol-?forum=mediafoundationdevelopment).

**Comment by tufeixp** [comment]
I am using https://github.com/SuslikV/cfg-cam to do the job through directShow api, you should look into it :)

**Comment by tufeixp** [comment]
according to messages from here, looks like IID_IAMCameraControl is still working:
https://social.msdn.microsoft.com/Forums/Windowsdesktop/en-US/4215d015-161b-45f3-8de4-9975b3925cc4/is-there-a-way-to-turn-off-auto-focus-and-auto-exposure-with-windows-media-foundation?forum=windowscompatibility
But I can not find any sample project running.

**Comment by olokobayusuf** [comment]
We will revisit this later on!
